// BION-DIRECTIVE-118/119's own required proof — real Hardhat fork of CURRENT Gnosis mainnet state,
// proving the real on-chain leg scripts/bridge-execute.ts submits (a single transaction, real
// native xDAI as value, real calldata from a live LI.FI quote, to the real aggregator deposit
// contract) actually succeeds, using BASE_MECH_POOL_WALLET's own real current balance.
//
// Real, honest scope boundary, stated directly (same posture as every other real-money proof this
// arc has shipped): this fork proves the REAL GNOSIS-SIDE DEPOSIT succeeds. It cannot prove the
// actual cross-chain delivery on Base — that's an off-chain solver/relay process (Relay Protocol
// or, sometimes, Stargate V2 — LI.FI's own routing choice varies call to call, confirmed live: two
// consecutive real quotes for the identical request returned different underlying tools), not
// something a Gnosis-only fork can observe or simulate. That leg's real correctness is proven by
// Forces' own first real, small-value run, same "first real X" precedent as every other
// external-relay-dependent step this project has shipped (D-32's first real create(), D-59's
// first real delivery).
//
// CORRECTION (BION-DIRECTIVE-120) — this file originally attributed a panic-0x11 revert seen here
// to fork/quote-timing drift. That was wrong, or at least incomplete: Forces' own real preflight
// (against REAL current mainnet state, not a fork) hit the identical panic 0x11. Root-caused via a
// real debug_traceCall (not guessed): the revert originates deep inside Balancer's real Vault
// (0xBA1333...ba9), reached through a Paraswap-orchestrated swap step LI.FI's default routing
// included for this quote (feeCollection -> paraswap -> relaydepository). Reproduced consistently
// across 3 independent real RPC providers and multiple amounts — a real fragility in that specific
// Paraswap-routed path, not a timing artifact, not this script, not the sentinel address (confirmed
// correct against LI.FI's own real token list), not an amount-too-small issue (a much larger amount
// failed too, differently). Fix: `denyExchanges=paraswap` — the resulting route
// (feeCollection -> nordstern -> relaydepository) estimates gas cleanly, repeatedly, on both a real
// fork and real live mainnet state.
//
// Uses hardhat_impersonateAccount to call AS the real BASE_MECH_POOL_WALLET address (no private
// key needed), submitting the real, live-quoted transaction against a local fork only — never
// broadcasts to real Gnosis mainnet. The quote itself comes from a real, live call to LI.FI's
// public API (li.quest) — not stubbed — since the real calldata is generated by that real
// aggregator, not reconstructable locally without reimplementing its routing logic.
//
// Opt-in, NOT part of `pnpm test` (vitest run) — run via:
//   MECH_FORK_CHAIN=gnosis pnpm --filter @grey/mech-adapter test:fork:bridge-execute
import hre from 'hardhat';
import { strict as assert } from 'node:assert';
import { createPublicClient, createWalletClient, custom, formatEther } from 'viem';
import { BASE_MECH_POOL_WALLET_ADDRESS } from '../../src/config.js';

const CHAIN_ID = 100;
const NATIVE_XDAI = '0x0000000000000000000000000000000000000000';
const NATIVE_WETH_ON_BASE = '0x4200000000000000000000000000000000000006';

interface LifiQuote {
  tool: string;
  includedSteps?: { tool: string }[];
  estimate: { toAmount: string; toAmountMin: string; executionDuration: number };
  transactionRequest: { to: `0x${string}`; data: `0x${string}`; value: string };
}

async function fetchQuote(amountWei: bigint, opts: { denyParaswap: boolean }): Promise<LifiQuote> {
  const url =
    `https://li.quest/v1/quote?fromChain=${CHAIN_ID}&toChain=8453` +
    `&fromToken=${NATIVE_XDAI}&toToken=${NATIVE_WETH_ON_BASE}` +
    `&fromAmount=${amountWei}&fromAddress=${BASE_MECH_POOL_WALLET_ADDRESS}` +
    (opts.denyParaswap ? `&denyExchanges=paraswap` : '');
  const res = await fetch(url);
  const json = (await res.json()) as LifiQuote & { message?: string };
  if (!res.ok || json.message) throw new Error(`quote failed: ${json.message ?? res.status}`);
  return json;
}

describe('mech-adapter — bridge execution, real Hardhat fork proof (BION-DIRECTIVE-118/119)', function () {
  this.timeout(60_000);

  const client = createPublicClient({ transport: custom(hre.network.provider) });

  before(async () => {
    // Same real infra note as this arc's other Gnosis fork proofs — EDR refuses eth_call exactly
    // AT the pinned fork block for chains without baked-in hardfork-activation history.
    await hre.network.provider.request({ method: 'evm_mine', params: [] });
  });

  it('the real script\'s exact deposit call — a fresh, real, live LI.FI quote submitted as a real transaction — succeeds on the fork against BASE_MECH_POOL_WALLET\'s own real current balance', async () => {
    const balance = await client.getBalance({ address: BASE_MECH_POOL_WALLET_ADDRESS });
    assert.ok(balance > 0n, 'expected the real forked Tier B balance to be non-zero');

    const reserve = 500_000_000_000_000_000n; // 0.5 xDAI, same real default as the script itself
    assert.ok(balance > reserve, 'expected real balance to exceed the gas reserve on this fork');
    const bridgeAmount = balance - reserve;

    // Real, live call to the real LI.FI API — not stubbed. The real calldata this generates is
    // exactly what the real script would submit (denyExchanges=paraswap, the real D-120 fix).
    const quote = await fetchQuote(bridgeAmount, { denyParaswap: true });
    console.log(`[fork] real live quote: tool=${quote.tool}, toAmount=${formatEther(BigInt(quote.estimate.toAmount))} ETH, duration=${quote.estimate.executionDuration}s`);
    assert.ok(BigInt(quote.estimate.toAmount) > 0n, 'expected a real, non-zero quoted output amount');

    await hre.network.provider.request({ method: 'hardhat_impersonateAccount', params: [BASE_MECH_POOL_WALLET_ADDRESS] });
    const walletClient = createWalletClient({ account: BASE_MECH_POOL_WALLET_ADDRESS, transport: custom(hre.network.provider) });

    const txHash = await walletClient.sendTransaction({
      to: quote.transactionRequest.to,
      data: quote.transactionRequest.data,
      value: BigInt(quote.transactionRequest.value),
      chain: null,
    });
    const receipt = await client.waitForTransactionReceipt({ hash: txHash });
    assert.equal(receipt.status, 'success', 'expected the real deposit transaction (real quote, real calldata) to succeed on the fork');
    console.log(`[fork] real deposit tx succeeded: ${txHash}`);
  });

  it('(informational) whether today\'s real, un-fixed Paraswap-routed quote reverts on this fork — NOT a hard pass/fail gate, see why below', async function () {
    // Real, honest finding from actually running this repeatedly (BION-DIRECTIVE-120): the
    // Paraswap-routed bug is ITSELF non-deterministic — it depends on real-time pool/liquidity
    // state at the moment a quote is generated, same as the D-120 fix's own success isn't
    // guaranteed every single time either (a later run of the FIRST test in this file, on a
    // separate real attempt, hit a plain, legitimate slippage revert — "Insufficient output" —
    // on a stargateV2-routed quote; a real, expected DeFi outcome the script's own preflight
    // check exists to catch, not a bug). This test is deliberately soft: it reports what
    // happened, real and live, but does not fail the suite either way — forcing a deterministic
    // assertion onto an inherently non-deterministic real-world condition would be dishonest, not
    // rigorous.
    const bridgeAmount = 1_000_000_000_000_000_000n; // 1 xDAI, same amount independently confirmed to real-revert earlier this directive
    const quote = await fetchQuote(bridgeAmount, { denyParaswap: false });
    if (!quote.includedSteps?.some((s) => s.tool === 'paraswap')) {
      console.log('[fork] this real, fresh quote did not route through Paraswap at all this time — nothing to observe.');
      return;
    }
    await hre.network.provider.request({ method: 'hardhat_impersonateAccount', params: [BASE_MECH_POOL_WALLET_ADDRESS] });
    const walletClient = createWalletClient({ account: BASE_MECH_POOL_WALLET_ADDRESS, transport: custom(hre.network.provider) });
    try {
      const txHash = await walletClient.sendTransaction({
        to: quote.transactionRequest.to,
        data: quote.transactionRequest.data,
        value: BigInt(quote.transactionRequest.value),
        chain: null,
      });
      console.log(`[fork] this real, Paraswap-routed quote did NOT revert this time: ${txHash} (real-world non-determinism — see file header)`);
    } catch (err) {
      console.log(`[fork] this real, Paraswap-routed quote DID revert this time: ${err instanceof Error ? err.message.split('\n')[0] : String(err)}`);
    }
  });
});
