// Codegen: src/{responses,requests}/v1/*.schema.json -> src/generated/v1[/requests]/*.d.ts
// Run: pnpm -C packages/grey-schemas codegen  (or `pnpm codegen` inside the package)
// Output is COMMITTED and enforced byte-identical by the CI codegen-drift job.
// Deterministic: static per-group banner, sorted file order, no timestamps.
//
// M3 (FDQ-3): structurally extended from the single-dir responses codegen to a group list.
// The responses group is byte-identical to the pre-M3 output (same banner string, same dir,
// same options, same NAME_MAP) so the frozen response .d.ts do not drift; the requests group
// is additive.
import { compileFromFile } from 'json-schema-to-typescript';
import { readdirSync, writeFileSync, mkdirSync } from 'node:fs';
import { join } from 'node:path';

interface CodegenGroup {
  label: string;
  schemaDir: string;
  outDir: string;
  bannerSource: string; // the "from <...>" clause; kept per-group so response banners stay byte-identical
  nameMap: Record<string, string>;
}

const SRC = join(import.meta.dirname, '..', 'src');

const banner = (bannerSource: string): string =>
  `/* eslint-disable */\n/**\n * AUTO-GENERATED by \`pnpm codegen\` from ${bannerSource}.\n * DO NOT EDIT BY HAND. Re-run codegen to regenerate.\n */`;

const GROUPS: CodegenGroup[] = [
  {
    label: 'responses',
    schemaDir: join(SRC, 'responses', 'v1'),
    outDir: join(SRC, 'generated', 'v1'),
    bannerSource: 'src/responses/v1/*.schema.json',
    // Schema file -> generated type name (Q4 naming table, locked verbatim).
    nameMap: {
      'legitimacy_scan.schema.json': 'LegitimacyScanResponse',
      'verify_whitepaper.schema.json': 'VerifyWhitepaperResponse',
      'verify_full_tech.schema.json': 'VerifyFullTechResponse',
      'claim_extraction.schema.json': 'ClaimExtractionResponse',
      'claim_history.schema.json': 'ClaimHistoryResponse',
      'quick_protocol_facts.schema.json': 'QuickProtocolFactsResponse',
      'daily_tech_brief.schema.json': 'DailyTechBriefResponse',
      'daily_greenlight_list.schema.json': 'DailyGreenlightListResponse',
      'scam_alert_feed.schema.json': 'ScamAlertFeedResponse',
      'envelope.schema.json': 'GreyResponseEnvelope',
      '_shared.schema.json': '_shared',
    },
  },
  {
    label: 'requests',
    schemaDir: join(SRC, 'requests', 'v1'),
    outDir: join(SRC, 'generated', 'v1', 'requests'),
    bannerSource: 'src/requests/v1/*.schema.json',
    // 7 paid offerings (M3 FDQ-10 — the 2 free GETs take no input, no request schema).
    nameMap: {
      'legitimacy_scan.schema.json': 'LegitimacyScanRequest',
      'verify_whitepaper.schema.json': 'VerifyWhitepaperRequest',
      'verify_full_tech.schema.json': 'VerifyFullTechRequest',
      'claim_extraction.schema.json': 'ClaimExtractionRequest',
      'claim_history.schema.json': 'ClaimHistoryRequest',
      'quick_protocol_facts.schema.json': 'QuickProtocolFactsRequest',
      'daily_tech_brief.schema.json': 'DailyTechBriefRequest',
    },
  },
];

let total = 0;
for (const group of GROUPS) {
  mkdirSync(group.outDir, { recursive: true });
  const files = readdirSync(group.schemaDir)
    .filter((f) => f.endsWith('.schema.json'))
    .sort();
  for (const f of files) {
    const outName = group.nameMap[f];
    if (!outName) throw new Error(`No NAME_MAP entry for ${group.label}/${f}`);
    const ts = await compileFromFile(join(group.schemaDir, f), {
      cwd: group.schemaDir,
      bannerComment: banner(group.bannerSource),
      additionalProperties: false,
      declareExternallyReferenced: true,
      unreachableDefinitions: true,
      format: true,
    });
    writeFileSync(join(group.outDir, `${outName}.d.ts`), ts);
    console.log(`✓ ${group.label}/${f} -> generated/v1/${group.label === 'requests' ? 'requests/' : ''}${outName}.d.ts`);
    total++;
  }
}
console.log(`\nGenerated ${total} files across ${GROUPS.length} groups.`);
