// Codegen: src/responses/v1/*.schema.json -> src/generated/v1/*.d.ts
// Run: pnpm -C packages/grey-schemas codegen  (or `pnpm codegen` inside the package)
// Output is COMMITTED and enforced byte-identical by the CI codegen-drift job.
// Deterministic: static banner, sorted file order, no timestamps.
import { compileFromFile } from 'json-schema-to-typescript';
import { readdirSync, writeFileSync, mkdirSync } from 'node:fs';
import { join } from 'node:path';

const SCHEMA_DIR = join(import.meta.dirname, '..', 'src', 'responses', 'v1');
const OUT_DIR = join(import.meta.dirname, '..', 'src', 'generated', 'v1');

// Schema file -> generated type name (Q4 naming table, locked verbatim).
const NAME_MAP: Record<string, string> = {
  'legitimacy_scan.schema.json': 'LegitimacyScanResponse',
  'verify_whitepaper.schema.json': 'VerifyWhitepaperResponse',
  'verify_full_tech.schema.json': 'VerifyFullTechResponse',
  'claim_extraction.schema.json': 'ClaimExtractionResponse',
  'claim_history.schema.json': 'ClaimHistoryResponse',
  'quick_protocol_facts.schema.json': 'QuickProtocolFactsResponse',
  'daily_tech_brief.schema.json': 'DailyTechBriefResponse',
  'daily_greenlight_list.schema.json': 'DailyGreenlightListResponse',
  'scam_alert_feed.schema.json': 'ScamAlertFeedResponse',
  'envelope.schema.json': 'GreyResponseEnvelope',
  '_shared.schema.json': '_shared',
};

const BANNER =
  '/* eslint-disable */\n/**\n * AUTO-GENERATED by `pnpm codegen` from src/responses/v1/*.schema.json.\n * DO NOT EDIT BY HAND. Re-run codegen to regenerate.\n */';

mkdirSync(OUT_DIR, { recursive: true });

const files = readdirSync(SCHEMA_DIR)
  .filter((f) => f.endsWith('.schema.json'))
  .sort();

for (const f of files) {
  const outName = NAME_MAP[f];
  if (!outName) throw new Error(`No NAME_MAP entry for ${f}`);
  const ts = await compileFromFile(join(SCHEMA_DIR, f), {
    cwd: SCHEMA_DIR,
    bannerComment: BANNER,
    additionalProperties: false,
    declareExternallyReferenced: true,
    unreachableDefinitions: true,
    format: true,
  });
  writeFileSync(join(OUT_DIR, `${outName}.d.ts`), ts);
  console.log(`✓ ${f} -> generated/v1/${outName}.d.ts`);
}
console.log(`\nGenerated ${files.length} files into src/generated/v1/.`);
